version: '3.9'

services:
  database:
    container_name: drf_shop_project_database
    image: postgres
    ports:
      - 5432:5433
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  
  app:
    build:
      context: .
    image: app
    container_name: blog_api_project_django_app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --no-input --clear &&
             gunicorn DRf_shop.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    depends_on:
      - database
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=*
      - DATABASE-NAME=postgres
      - DATABASE-USER=postgres
      - DATABASE-PASSWORD=postgres
      - DATABASE-HOST=database
      - DATABASE-PORT=5432
  
  

volumes:
  postgres:
  static:
  media: